### ISSUE TITLE
您好 请教一个问题

### ISSUE THREAD

**Issue by jlala** [xwartz/vue-v2ex#2]
请问 使用 vue-cli 怎么把vue.js项目部署到生产环境上呢？
有使用 npm run build吗？
还是直接 pm2 npm run dev呢？
望指教！

**Comment by xwartz** [comment]
`npm run build` 会产生静态资源的，不过我已经很久不写 `vuejs` 了，你自己看下 `vue-cli`  产生的 `package.json` 是不是有 `build` 脚本

**Comment by jlala** [comment]
那你这边的生产环境是怎么部署的呢？

**Comment by xwartz** [comment]
`npm run build` 之后就可以部署了，我是静态网页，没有后端的。
